CREATE TABLE `service` (
  `id` int(20) NOT NULL auto_increment,
  `pin` int(22) NOT NULL,
  `area` varchar(22) NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (2,411051,'Anandnagar');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (3,411021,'Bavdhan');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (4,411037,'Bibvewadi');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (5,412109,'Dehu');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (6,411043,'Dhankawadi');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (7,411041,'Dhayari');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (8,411042,'Guruwar Peth');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (9,413106,'Hingangaon');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (10,411028,'Hadapsar');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (11,411057,'Infotech park (hinjawa');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (12,411052,'Karvenagar');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (14,412202,'Koregaon Mul');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (15,411038,'Kothrud');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (16,412201,'Loni Kalbhor');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (17,410401,'Lonavala');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (18,411048,'N I b m');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (19,411023,'N.D.a. khadakwasla');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (20,411016,'Gokhalenagar');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (21,411002,'Nana Peth');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (22,412107,'Panshet');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (23,411009,'Parvati');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (24,411001,'Pune');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (25,411001,'Pune Cantt east');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (26,411002,'Pune City ');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (27,411011,'Rasta Peth');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (28,411030,'S.P. college');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (29,411030,'Sadashiv Peth');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (30,411005,'Shivajinagar');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (31,411023,'Shivane');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (32,411042,'Swargate');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (33,410506,'Talegaon Dabhade');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (35,412202,'Urulikanchan');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (36,412106,'Vadgaon');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (37,411014,'Vadgaon Sheri');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (38,412207,'Vagholi');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (39,411015,'Vishrantwadi');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (40,411057,'Wakad');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (41,411058,'Warje ');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (42,411006,'Yerwada');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (43,411042,'Donje');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (44,411015,'Dhanori');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (45,411004,'Deccan Gymkhana');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (46,411001,'Dapodi');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (47,413801,'Daund');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (48,410501,'Chakan');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (49,411035,'Akurdi');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (50,411032,'Airport');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (51,411007,'Aundh');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (52,413102,'Baramati');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (55,411051,'Anandnagar');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (56,411021,'Bavdhan');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (57,411037,'Bibvewadi');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (58,412109,'Dehu');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (59,411043,'Dhankawadi');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (60,411041,'Dhayari');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (61,411042,'Guruwar Peth');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (62,413106,'Hingangaon');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (63,411028,'Hadapsar');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (64,411057,'Infotech park (hinjawa');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (65,411052,'Karvenagar');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (67,412202,'Koregaon Mul');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (68,411038,'Kothrud');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (69,412201,'Loni Kalbhor');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (70,410401,'Lonavala');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (71,411048,'N I b m');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (72,411023,'N.D.a. khadakwasla');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (73,411016,'Gokhalenagar');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (74,411002,'Nana Peth');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (75,412107,'Panshet');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (76,411009,'Parvati');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (77,411001,'Pune');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (78,411001,'Pune Cantt east');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (79,411002,'Pune City ');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (80,411011,'Rasta Peth');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (81,411030,'S.P. college');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (82,411030,'Sadashiv Peth');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (83,411005,'Shivajinagar');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (84,411023,'Shivane');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (85,411042,'Swargate');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (86,410506,'Talegaon Dabhade');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (88,412202,'Urulikanchan');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (89,412106,'Vadgaon');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (90,411014,'Vadgaon Sheri');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (91,412207,'Vagholi');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (92,411015,'Vishrantwadi');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (93,411057,'Wakad');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (94,411058,'Warje ');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (95,411006,'Yerwada');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (96,411042,'Donje');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (97,411015,'Dhanori');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (98,411004,'Deccan Gymkhana');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (99,411001,'Dapodi');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (100,413801,'Daund');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (101,410501,'Chakan');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (102,411035,'Akurdi');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (103,411032,'Airport');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (104,411007,'Aundh');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (105,413102,'Baramati');
insert into `db_healthcare`.`service`(`id`,`pin`,`area`) values (119,411024,'khadakwasla');
